enquete/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('votacoes/', include('votacoes.urls')),
    path('admin/', admin.site.urls),
]

votacoes/urls.py
from django.urls import path

from . import views

app_name = 'votacoes'

urlpatterns = [
    path('', views.index, name='index'), 
    path('<int:questao_id>/', views.detalhes, name='detalhes'),
    path('<int:questao_id>/resultados/', views.resultados, name='resultados'),
    path('<int:questao_id>/votar/', views.votar, name='votar'),
]

votacoes/models.py
from django.db import models
from django.utils import timezone

class Questao (models.Model):
    questao_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data de publicação')

    def __str__(self):
        return self.questao_text

    def foi_publicado_recentemente(self):
        return True 

class Opcao (models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_text = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.opcao_text

votacoes/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, Http404, get_object_or_404
from .models import Questao, Opcao

def index(request):
   list_ultimas_questoes = Questao.objects.order_by('-pub_date')[:5]
   context = {
      'lista_ultimas_questoes': list_ultimas_questoes
   }
   return render(request, 'votacoes/index.html', context)

def detalhes(request, questao_id):
   questao = get_object_or_404(Questao, pk=questao_id)
   return render(request, 'votacoes/detalhes.html', {'questao': questao})

def resultados(request, questao_id):
   html = "Você está olhando os resultados da questão %s. " 
   return HttpResponse(html % questao_id) 

def votar(request, questao_id):
   return HttpResponse("Você está votando na questão %s." % questao_id)

 

votacoes/templates/votacoes/detalhes.html
<h1>{{ questao.questao_text }}</h1>
{% if msg_erro %}<p><strong>{{ msg_erro}}</strong></p>{% endif %}

<form action="{% url 'votacoes:votar' questao_id %}" method="post">
{% csrf_token %}
{% for opcao in questao.opcao_st all %}
    <imput tipe="radio" name="opcao" id="opcao"{{ foorloop.counter }} value="{{ opcao.id }}">
    <label form="opcao{{ forloop.counter }}">{{ opcao.opcao_text }}</label><br>
{% endfor %}
    <imput tipe="submit" vallue="votar">
    
</form>

votacoes/templates/votacoes/index.html
{% if lista_ultimas_questoes %}
    <ul>
    {% for questao in lista_ultimas_questoes %}
        <li>
            <a href="{% url 'votacoes:detalhes' questao.id %}">
            {{ questao.questao_text }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>
        Não existem votações disponíveis
    </p>
{% endif %}